export const asyncTypes = Object.freeze({
  CREATE_USER_ASYNC: 'CREATE_USER_ASYNC',
  LOGIN_USER_ASYNC: 'LOGIN_USER_ASYNC',
  LOGOUT_USER_ASYNC: 'LOGOUT_USER_ASYNC',
  EDIT_USER_ASYNC: 'EDIT_USER_ASYNC',
});
